#!/bin/bash 
# convert fastq files into sorted bam files with tophat2 and samtools packages.
# Renyi Wu,    v0.3-added fastqc on 6-15-20.;
cd "$(dirname "$0")" #or cd "${0%/*}" or cd "${0%/*}"
# redirect stdout/stderr to a file
#exec &> log.txt
# OR else to redirect only stdout use: 
printf "working on...\n DO NOT CLOSE THIS TERMINAL!!"
exec >> logfile.txt 2>&1
date
echo "Currently in: ${0%/*} , with these file/folder(s)"
ls -hp
sleep 2m
